<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260820182834 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE site_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, send_cookies BOOLEAN NOT NULL, send_user_agent BOOLEAN NOT NULL, send_referrer BOOLEAN NOT NULL, downloader VARCHAR(255) NOT NULL, site_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64D05A53F6BD1646 ON site_setting (site_id)');
        $this->addSql('CREATE TABLE user_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C779A6927E3C61F9 ON user_setting (owner_id)');
        $this->addSql('CREATE TABLE user_site_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, send_cookies BOOLEAN NOT NULL, send_user_agent BOOLEAN NOT NULL, send_referrer BOOLEAN NOT NULL, downloader VARCHAR(255) NOT NULL, site_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E41C2651F6BD1646 ON user_site_setting (site_id)');
        $this->addSql('CREATE TABLE user_site_setting_oidc_subject_identifier (user_site_setting_id INT NOT NULL, oidc_subject_identifier_id INT NOT NULL, PRIMARY KEY (user_site_setting_id, oidc_subject_identifier_id))');
        $this->addSql('CREATE INDEX IDX_9B58AD74DCE05E38 ON user_site_setting_oidc_subject_identifier (user_site_setting_id)');
        $this->addSql('CREATE INDEX IDX_9B58AD7443F28551 ON user_site_setting_oidc_subject_identifier (oidc_subject_identifier_id)');
        $this->addSql('ALTER TABLE site_setting ADD CONSTRAINT FK_64D05A53F6BD1646 FOREIGN KEY (site_id) REFERENCES supported_site (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_setting ADD CONSTRAINT FK_C779A6927E3C61F9 FOREIGN KEY (owner_id) REFERENCES oidc_subject_identifier (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_site_setting ADD CONSTRAINT FK_E41C2651F6BD1646 FOREIGN KEY (site_id) REFERENCES supported_site (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_site_setting_oidc_subject_identifier ADD CONSTRAINT FK_9B58AD74DCE05E38 FOREIGN KEY (user_site_setting_id) REFERENCES user_site_setting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_site_setting_oidc_subject_identifier ADD CONSTRAINT FK_9B58AD7443F28551 FOREIGN KEY (oidc_subject_identifier_id) REFERENCES oidc_subject_identifier (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE site_setting DROP CONSTRAINT FK_64D05A53F6BD1646');
        $this->addSql('ALTER TABLE user_setting DROP CONSTRAINT FK_C779A6927E3C61F9');
        $this->addSql('ALTER TABLE user_site_setting DROP CONSTRAINT FK_E41C2651F6BD1646');
        $this->addSql('ALTER TABLE user_site_setting_oidc_subject_identifier DROP CONSTRAINT FK_9B58AD74DCE05E38');
        $this->addSql('ALTER TABLE user_site_setting_oidc_subject_identifier DROP CONSTRAINT FK_9B58AD7443F28551');
        $this->addSql('DROP TABLE site_setting');
        $this->addSql('DROP TABLE user_setting');
        $this->addSql('DROP TABLE user_site_setting');
        $this->addSql('DROP TABLE user_site_setting_oidc_subject_identifier');
    }
}
